
-- inner join, left, rigth

SELECT	TB_AUTOR.COD_AUT AS 'CODIGO',
        TB_AUTOR.NOME_AUT AS 'NOME AUTOR',
		TB_LIVRO.COD_LIV AS 'COD',
		TB_LIVRO.TITULO_LIV AS 'TITULO'
FROM TB_AUTOR INNER JOIN TB_AUTO_LIVRO
 ON TB_AUTOR.COD_AUT = TB_AUTO_LIVRO.COD_AUT
INNER  JOIN TB_LIVRO 
  ON TB_LIVRO.COD_LIV = TB_AUTO_LIVRO.COD_LIV
  ORDER BY TB_AUTOR.NOME_AUT;

  -- Exercicios de fixação
  /*
   Mostrar os Autores que publicaram 
   certos livros de certas editoras

   10 min;
   	    */

SELECT	TB_AUTOR.COD_AUT AS 'CODIGO',
        TB_AUTOR.NOME_AUT AS 'NOME AUTOR',
		TB_LIVRO.COD_LIV AS 'COD',
		TB_LIVRO.TITULO_LIV AS 'TITULO',
		TB_EDITORA.NOME_ED AS 'EDITORA'
FROM TB_AUTOR INNER JOIN TB_AUTO_LIVRO
  ON TB_AUTOR.COD_AUT = TB_AUTO_LIVRO.COD_AUT
INNER  JOIN TB_LIVRO 
  ON TB_LIVRO.COD_LIV = TB_AUTO_LIVRO.COD_LIV
INNER  JOIN TB_ED_LIV 
  ON TB_LIVRO.COD_LIV = TB_ED_LIV.COD_LIV
INNER  JOIN TB_EDITORA 
  ON TB_EDITORA.COD_ED = TB_ED_LIV.COD_ED
 ORDER BY TB_AUTOR.NOME_AUT;


 // LEFT

 SELECT TB_CLIENTE.COD_CLI,
        TB_CLIENTE.NOME_CLI,
		TB_FISICA.CPF_CLI
FROM TB_CLIENTE LEFT JOIN TB_FISICA
ON TB_CLIENTE.COD_CLI = TB_FISICA.COD_CLI

